services:
  data:
    build:
      context: ./data/etl
    container_name: etl_pipeline
    volumes:
      - ./data/etl:/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    entrypoint: ["python3", "main.py"]
    command: ["7", "--postgres", "--s3"]